# Generated by Django 6.0.5 on 2026-05-23 13:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Название мероприятия",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "date",
                    models.DateTimeField(
                        db_index=True, verbose_name="Дата и время проведения"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=500, verbose_name="Место проведения"),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "location_lon",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость билета",
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Максимальное количество мест"
                    ),
                ),
                (
                    "registered_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Зарегистрировано участников"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("concert", "Концерты"),
                            ("theater", "Театр"),
                            ("workshop", "Мастер-классы"),
                            ("exhibition", "Выставки"),
                            ("festival", "Фестивали"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликовано"),
                            ("cancelled", "Отменено"),
                            ("completed", "Завершено"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/%Y/%m/%d/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["date", "status"], name="core_event_date_f4bfe0_idx"
                    ),
                    models.Index(
                        fields=["category", "status"],
                        name="core_event_categor_60a73d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "spots",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Количество мест",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("rejected", "Отклонено"),
                            ("cancelled", "Отменено пользователем"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        unique=True,
                        verbose_name="Ключ идемпотентности",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата подтверждения"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="core.event",
                        verbose_name="Мероприятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регистрация",
                "verbose_name_plural": "Регистрации",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "status"],
                        name="core_regist_event_i_f22993_idx",
                    ),
                    models.Index(
                        fields=["email", "status"], name="core_regist_email_6866f3_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="core_regist_created_916ae6_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "email"),
                        name="unique_email_per_event",
                        violation_error_message="На это мероприятие уже зарегистрирован данный email",
                    )
                ],
            },
        ),
    ]
